### ISSUE TITLE
Could not clone on Windows

### ISSUE THREAD

**Issue by Donny-H** [joshnuss/svelte-supabase#4]
Any ideas on this? Brand new Sveltekit skeleton. Using node v16 (could be the issue?)

```
npx svelte-add joshnuss/svelte-supabase
[ info ]  Applying preset joshnuss/svelte-supabase.
[ error ]  Could not clone joshnuss/svelte-supabase.
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Object.action (C:\Users\donho\Desktop\lol\node_modules\simple-git\src\lib\plugins\error-detection.plugin.js:30:33)
    at PluginStore.exec (C:\Users\donho\Desktop\lol\node_modules\simple-git\src\lib\plugins\plugin-store.js:21:33)
    at C:\Users\donho\Desktop\lol\node_modules\simple-git\src\lib\runners\git-executor-chain.js:92:45
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (C:\Users\donho\Desktop\lol\node_modules\simple-git\src\lib\runners\git-executor-chain.js:90:16)
    at GitExecutorChain.<anonymous> (C:\Users\donho\Desktop\lol\node_modules\simple-git\src\lib\runners\git-executor-chain.js:74:46)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\donho\Desktop\lol\node_modules\simple-git\src\lib\runners\git-executor-chain.js:5:58)
```

**Comment by joshnuss** [comment]
Hi @Donny-H,

Tested it with node 16.1.0 and it worked fine. 
I see you're on Windows, maybe it's related to that? I haven't tested it yet on Windows.

There is a similar issue here: https://github.com/svelte-add/svelte-add/issues/27

**Comment by Donny-H** [comment]
@joshnuss 

Yup, tried it on my linux box with no issue. Would assume it's a windows bug like you said. I can work around it for now. Thanks!

**Comment by babichjacob** [comment]
I think it is always the case if you get this error it's because you need to install `git`.

**Comment by joshnuss** [comment]
Thanks @babichjacob :+1: 

@Donny-H can you confirm if you've got git installed?

**Comment by Donny-H** [comment]
> Thanks @babichjacob 👍
> 
> @Donny-H can you confirm if you've got git installed?

No longer on that particular pc but I think not since it was a fairly new win install. Probably safe to close. Maybe add to readme  as well to ensure git is installed. Thanks 👍

**Comment by babichjacob** [comment]
> Maybe add to readme  as well to ensure git is installed. Thanks 👍

I'll do this in core `svelte-add`'s code when it detects this error rather than putting it in all the READMEs.

**Comment by joshnuss** [comment]
Thanks @babichjacob, that would be even better :raised_hands:
